version: '3.8'

services:
  qdrant-db:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant-db
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant_data

  django-app:
    build: .
    ports:
      - "8000:8000"  
    environment:
      QDRANT_HOST: qdrant-db 
    depends_on:
      - qdrant-db

